apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpMethod: GET
- name: Tempo (yes streaming)
  type: tempo
  access: proxy
  orgId: 1
  url: http://query-frontend:3200
  basicAuth: false
  isDefault: true
  version: 0 # Reapply protected settings on startup even when the existing datasource version advanced.
  editable: false
  apiVersion: 1
  uid: tempo-streaming-enabled
  jsonData:
    protectedAttributesEnabled: true
    protectedAttributesSubstringEnabled: true
    redactionSchedulerURL: http://backend-scheduler:9095
    httpHeaderName1: X-Scope-OrgID
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
    streamingEnabled:
      search: true
      metrics: true
- name: Tempo (no streaming)
  type: tempo
  access: proxy
  orgId: 1
  url: http://query-frontend:3200
  basicAuth: false
  isDefault: false
  version: 0
  editable: false
  apiVersion: 1
  uid: tempo-streaming-disabled
  jsonData:
    protectedAttributesEnabled: true
    protectedAttributesSubstringEnabled: true
    redactionSchedulerURL: http://backend-scheduler:9095
    httpHeaderName1: X-Scope-OrgID
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus