// Code generated by goyacc -l -o pkg/traceql/expr.y.go pkg/traceql/expr.y. DO NOT EDIT.
package traceql

import __yyfmt__ "fmt"

import (
	"math"
	"time"
)

type yySymType struct {
	yys               int
	root              RootExpr
	metricsExpression *RootExpr
	groupOperation    GroupOperation
	coalesceOperation CoalesceOperation
	selectOperation   SelectOperation
	attributeList     []Attribute

	spansetExpression         SpansetExpression
	spansetPipelineExpression SpansetExpression
	wrappedSpansetPipeline    Pipeline
	spansetPipeline           Pipeline
	spansetFilter             *SpansetFilter
	scalarFilter              ScalarFilter
	scalarFilterOperation     Operator

	scalarPipelineExpressionFilter ScalarFilter
	scalarPipelineExpression       ScalarExpression
	scalarExpression               ScalarExpression
	wrappedScalarPipeline          Pipeline
	scalarPipeline                 Pipeline
	aggregate                      Aggregate
	metricsAggregation             firstStageElement
	metricsSecondStage             secondStageElement
	metricsSecondStagePipeline     ChainedSecondStage

	fieldExpression      FieldExpression
	static               Static
	intrinsicField       Attribute
	attributeField       Attribute
	attribute            Attribute
	scopedIntrinsicField Attribute

	binOp          Operator
	staticInt      int
	staticStr      string
	staticFloat    float64
	staticDuration time.Duration
	numericList    []float64

	hint     *Hint
	hintList []*Hint
	hints    *Hints
}

const IDENTIFIER = 57346
const STRING = 57347
const INTEGER = 57348
const FLOAT = 57349
const DURATION = 57350
const DOT = 57351
const OPEN_BRACE = 57352
const CLOSE_BRACE = 57353
const OPEN_PARENS = 57354
const CLOSE_PARENS = 57355
const COMMA = 57356
const NIL = 57357
const TRUE = 57358
const FALSE = 57359
const STATUS_ERROR = 57360
const STATUS_OK = 57361
const STATUS_UNSET = 57362
const KIND_UNSPECIFIED = 57363
const KIND_INTERNAL = 57364
const KIND_SERVER = 57365
const KIND_CLIENT = 57366
const KIND_PRODUCER = 57367
const KIND_CONSUMER = 57368
const IDURATION = 57369
const CHILDCOUNT = 57370
const NAME = 57371
const STATUS = 57372
const STATUS_MESSAGE = 57373
const PARENT = 57374
const KIND = 57375
const ROOTNAME = 57376
const ROOTSERVICENAME = 57377
const ROOTSERVICE = 57378
const TRACEDURATION = 57379
const NESTEDSETLEFT = 57380
const NESTEDSETRIGHT = 57381
const NESTEDSETPARENT = 57382
const ID = 57383
const TRACE_ID = 57384
const SPAN_ID = 57385
const PARENT_ID = 57386
const TIMESINCESTART = 57387
const VERSION = 57388
const PARENT_DOT = 57389
const RESOURCE_DOT = 57390
const SPAN_DOT = 57391
const TRACE_COLON = 57392
const SPAN_COLON = 57393
const EVENT_COLON = 57394
const EVENT_DOT = 57395
const LINK_COLON = 57396
const LINK_DOT = 57397
const INSTRUMENTATION_COLON = 57398
const INSTRUMENTATION_DOT = 57399
const COUNT = 57400
const AVG = 57401
const MAX = 57402
const MIN = 57403
const SUM = 57404
const BY = 57405
const COALESCE = 57406
const SELECT = 57407
const END_ATTRIBUTE = 57408
const RATE = 57409
const COUNT_OVER_TIME = 57410
const MIN_OVER_TIME = 57411
const MAX_OVER_TIME = 57412
const AVG_OVER_TIME = 57413
const SUM_OVER_TIME = 57414
const QUANTILE_OVER_TIME = 57415
const HISTOGRAM_OVER_TIME = 57416
const COMPARE = 57417
const TOPK = 57418
const BOTTOMK = 57419
const WITH = 57420
const PIPE = 57421
const AND = 57422
const OR = 57423
const EQ = 57424
const NEQ = 57425
const LT = 57426
const LTE = 57427
const GT = 57428
const GTE = 57429
const NRE = 57430
const RE = 57431
const DESC = 57432
const ANCE = 57433
const SIBL = 57434
const NOT_CHILD = 57435
const NOT_PARENT = 57436
const NOT_DESC = 57437
const NOT_ANCE = 57438
const UNION_CHILD = 57439
const UNION_PARENT = 57440
const UNION_DESC = 57441
const UNION_ANCE = 57442
const UNION_SIBL = 57443
const ADD = 57444
const SUB = 57445
const NOT = 57446
const MUL = 57447
const DIV = 57448
const MOD = 57449
const POW = 57450

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"INTEGER",
	"FLOAT",
	"DURATION",
	"DOT",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_PARENS",
	"CLOSE_PARENS",
	"COMMA",
	"NIL",
	"TRUE",
	"FALSE",
	"STATUS_ERROR",
	"STATUS_OK",
	"STATUS_UNSET",
	"KIND_UNSPECIFIED",
	"KIND_INTERNAL",
	"KIND_SERVER",
	"KIND_CLIENT",
	"KIND_PRODUCER",
	"KIND_CONSUMER",
	"IDURATION",
	"CHILDCOUNT",
	"NAME",
	"STATUS",
	"STATUS_MESSAGE",
	"PARENT",
	"KIND",
	"ROOTNAME",
	"ROOTSERVICENAME",
	"ROOTSERVICE",
	"TRACEDURATION",
	"NESTEDSETLEFT",
	"NESTEDSETRIGHT",
	"NESTEDSETPARENT",
	"ID",
	"TRACE_ID",
	"SPAN_ID",
	"PARENT_ID",
	"TIMESINCESTART",
	"VERSION",
	"PARENT_DOT",
	"RESOURCE_DOT",
	"SPAN_DOT",
	"TRACE_COLON",
	"SPAN_COLON",
	"EVENT_COLON",
	"EVENT_DOT",
	"LINK_COLON",
	"LINK_DOT",
	"INSTRUMENTATION_COLON",
	"INSTRUMENTATION_DOT",
	"COUNT",
	"AVG",
	"MAX",
	"MIN",
	"SUM",
	"BY",
	"COALESCE",
	"SELECT",
	"END_ATTRIBUTE",
	"RATE",
	"COUNT_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"HISTOGRAM_OVER_TIME",
	"COMPARE",
	"TOPK",
	"BOTTOMK",
	"WITH",
	"PIPE",
	"AND",
	"OR",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"NRE",
	"RE",
	"DESC",
	"ANCE",
	"SIBL",
	"NOT_CHILD",
	"NOT_PARENT",
	"NOT_DESC",
	"NOT_ANCE",
	"UNION_CHILD",
	"UNION_PARENT",
	"UNION_DESC",
	"UNION_ANCE",
	"UNION_SIBL",
	"ADD",
	"SUB",
	"NOT",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 335,
	13, 88,
	-2, 96,
}

const yyPrivate = 57344

const yyLast = 1358

var yyAct = [...]int{

	111, 7, 20, 9, 108, 383, 307, 110, 8, 14,
	311, 227, 266, 99, 309, 331, 2, 86, 55, 247,
	380, 248, 271, 270, 253, 254, 74, 255, 256, 257,
	266, 222, 109, 222, 163, 404, 166, 255, 256, 257,
	266, 164, 15, 103, 401, 258, 259, 260, 261, 262,
	263, 265, 264, 78, 32, 31, 162, 6, 87, 88,
	89, 90, 91, 92, 461, 253, 254, 75, 255, 256,
	257, 266, 96, 97, 98, 99, 384, 385, 94, 95,
	407, 96, 97, 98, 99, 230, 377, 94, 95, 406,
	96, 97, 98, 99, 373, 372, 376, 400, 371, 223,
	94, 95, 251, 96, 97, 98, 99, 368, 367, 250,
	366, 365, 438, 203, 205, 206, 207, 208, 209, 210,
	211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
	83, 84, 85, 86, 249, 434, 238, 240, 241, 242,
	243, 244, 245, 433, 246, 228, 474, 432, 269, 431,
	272, 273, 417, 267, 268, 258, 259, 260, 261, 262,
	263, 265, 264, 267, 268, 258, 259, 260, 261, 262,
	263, 265, 264, 416, 470, 253, 254, 422, 255, 256,
	257, 266, 299, 441, 277, 253, 254, 440, 255, 256,
	257, 266, 52, 53, 54, 55, 423, 375, 336, 300,
	302, 303, 304, 305, 81, 82, 421, 83, 84, 85,
	86, 50, 51, 333, 52, 53, 54, 55, 420, 329,
	386, 387, 388, 297, 298, 163, 335, 166, 278, 279,
	419, 161, 164, 328, 50, 51, 6, 52, 53, 54,
	55, 473, 341, 469, 341, 381, 225, 338, 313, 314,
	315, 316, 317, 318, 6, 87, 88, 89, 90, 91,
	92, 328, 467, 341, 267, 268, 258, 259, 260, 261,
	262, 263, 265, 264, 418, 81, 82, 295, 83, 84,
	85, 86, 329, 466, 341, 399, 253, 254, 6, 255,
	256, 257, 266, 296, 465, 341, 391, 342, 343, 344,
	345, 346, 347, 349, 351, 352, 353, 354, 355, 356,
	357, 358, 359, 390, 361, 363, 301, 389, 464, 341,
	382, 226, 251, 251, 251, 251, 251, 251, 468, 250,
	250, 250, 250, 250, 250, 81, 82, 398, 83, 84,
	85, 86, 251, 392, 393, 394, 395, 396, 397, 250,
	333, 403, 450, 338, 249, 249, 249, 249, 249, 249,
	454, 341, 283, 405, 21, 22, 23, 447, 19, 284,
	176, 285, 453, 341, 249, 78, 286, 78, 451, 452,
	78, 449, 448, 424, 425, 409, 408, 410, 19, 75,
	204, 75, 310, 446, 75, 313, 314, 315, 316, 317,
	318, 445, 163, 163, 166, 166, 163, 335, 166, 164,
	164, 378, 379, 164, 382, 93, 25, 28, 26, 27,
	29, 16, 177, 17, 340, 341, 444, 430, 80, 429,
	251, 251, 412, 411, 330, 327, 326, 250, 250, 325,
	324, 323, 322, 321, 320, 251, 251, 251, 251, 442,
	443, 251, 250, 250, 250, 250, 319, 231, 250, 197,
	179, 24, 249, 249, 455, 456, 457, 458, 160, 251,
	462, 159, 158, 157, 156, 155, 250, 249, 249, 249,
	249, 101, 100, 249, 413, 414, 415, 19, 471, 460,
	459, 127, 112, 113, 114, 117, 140, 472, 102, 104,
	463, 249, 105, 115, 116, 119, 118, 120, 121, 122,
	123, 124, 125, 126, 128, 439, 129, 130, 131, 133,
	132, 134, 135, 428, 136, 137, 138, 139, 152, 153,
	154, 437, 436, 427, 143, 141, 142, 147, 148, 149,
	144, 150, 145, 151, 146, 308, 370, 369, 282, 127,
	112, 113, 114, 117, 140, 281, 280, 104, 276, 275,
	364, 115, 116, 119, 118, 120, 121, 122, 123, 124,
	125, 126, 128, 274, 129, 130, 131, 133, 132, 134,
	135, 30, 136, 137, 138, 139, 306, 435, 77, 18,
	106, 107, 143, 141, 142, 147, 148, 149, 144, 150,
	145, 151, 146, 4, 13, 312, 11, 127, 112, 113,
	114, 117, 140, 165, 1, 104, 0, 0, 362, 115,
	116, 119, 118, 120, 121, 122, 123, 124, 125, 126,
	128, 0, 129, 130, 131, 133, 132, 134, 135, 0,
	136, 137, 138, 139, 0, 0, 0, 0, 106, 107,
	143, 141, 142, 147, 148, 149, 144, 150, 145, 151,
	146, 0, 0, 0, 0, 127, 112, 113, 114, 117,
	140, 0, 0, 104, 0, 0, 105, 115, 116, 119,
	118, 120, 121, 122, 123, 124, 125, 126, 128, 0,
	129, 130, 131, 133, 132, 134, 135, 0, 136, 137,
	138, 139, 0, 0, 0, 0, 106, 107, 143, 141,
	142, 147, 148, 149, 144, 150, 145, 151, 146, 0,
	0, 0, 0, 127, 112, 113, 114, 117, 140, 0,
	0, 104, 0, 0, 350, 115, 116, 119, 118, 120,
	121, 122, 123, 124, 125, 126, 128, 0, 129, 130,
	131, 133, 132, 134, 135, 0, 136, 137, 138, 139,
	0, 0, 0, 0, 106, 107, 143, 141, 142, 147,
	148, 149, 144, 150, 145, 151, 146, 374, 0, 0,
	0, 127, 112, 113, 114, 117, 140, 0, 0, 104,
	0, 426, 348, 115, 116, 119, 118, 120, 121, 122,
	123, 124, 125, 126, 128, 0, 129, 130, 131, 133,
	132, 134, 135, 0, 136, 137, 138, 139, 0, 0,
	0, 0, 106, 107, 143, 141, 142, 147, 148, 149,
	144, 150, 145, 151, 146, 21, 22, 23, 0, 19,
	0, 176, 252, 0, 267, 268, 258, 259, 260, 261,
	262, 263, 265, 264, 360, 0, 0, 381, 0, 0,
	313, 314, 315, 316, 317, 318, 253, 254, 0, 255,
	256, 257, 266, 0, 0, 0, 0, 0, 0, 0,
	106, 107, 0, 339, 0, 0, 0, 25, 28, 26,
	27, 29, 16, 177, 17, 227, 167, 168, 169, 170,
	172, 171, 173, 174, 175, 0, 0, 0, 0, 0,
	0, 267, 268, 258, 259, 260, 261, 262, 263, 265,
	264, 267, 268, 258, 259, 260, 261, 262, 263, 265,
	264, 224, 24, 253, 254, 0, 255, 256, 257, 266,
	79, 5, 0, 253, 254, 0, 255, 256, 257, 266,
	267, 268, 258, 259, 260, 261, 262, 263, 265, 264,
	221, 0, 0, 0, 87, 88, 89, 90, 91, 92,
	0, 0, 253, 254, 0, 255, 256, 257, 266, 0,
	0, 0, 0, 0, 94, 95, 0, 96, 97, 98,
	99, 196, 198, 199, 200, 201, 202, 0, 56, 61,
	0, 0, 58, 0, 57, 0, 65, 0, 59, 60,
	62, 63, 64, 67, 66, 68, 69, 72, 71, 70,
	0, 0, 0, 0, 0, 0, 0, 33, 38, 0,
	0, 35, 0, 34, 0, 44, 0, 36, 37, 39,
	40, 41, 42, 43, 45, 46, 47, 48, 49, 56,
	61, 76, 12, 58, 0, 57, 0, 65, 0, 59,
	60, 62, 63, 64, 67, 66, 68, 69, 72, 71,
	70, 33, 38, 0, 0, 35, 0, 34, 0, 44,
	0, 36, 37, 39, 40, 41, 42, 43, 45, 46,
	47, 48, 49, 21, 22, 23, 0, 19, 0, 337,
	0, 21, 22, 23, 0, 19, 0, 334, 0, 21,
	22, 23, 58, 19, 57, 332, 65, 0, 59, 60,
	62, 63, 64, 67, 66, 68, 69, 72, 71, 70,
	0, 0, 229, 232, 233, 234, 235, 236, 237, 402,
	0, 0, 0, 0, 0, 25, 28, 26, 27, 29,
	16, 0, 17, 25, 28, 26, 27, 29, 16, 0,
	17, 25, 28, 26, 27, 29, 16, 35, 17, 34,
	0, 44, 0, 36, 37, 39, 40, 41, 42, 43,
	45, 46, 47, 48, 49, 21, 22, 23, 0, 19,
	24, 10, 0, 21, 22, 23, 0, 19, 24, 176,
	0, 21, 22, 23, 0, 310, 24, 239, 313, 314,
	315, 316, 317, 318, 0, 287, 294, 288, 290, 291,
	0, 289, 0, 0, 0, 0, 0, 0, 0, 292,
	73, 3, 293, 0, 0, 0, 0, 25, 28, 26,
	27, 29, 16, 0, 17, 25, 28, 26, 27, 29,
	0, 0, 0, 25, 28, 26, 27, 29, 0, 0,
	0, 0, 0, 140, 178, 180, 181, 182, 183, 184,
	185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
	195, 128, 24, 129, 130, 131, 133, 132, 134, 135,
	24, 136, 137, 138, 139, 0, 0, 0, 24, 0,
	0, 143, 141, 142, 147, 148, 149, 144, 150, 145,
	151, 146, 127, 112, 113, 114, 117, 0, 0, 0,
	231, 0, 0, 0, 115, 116, 119, 118, 120, 121,
	122, 123, 124, 125, 126, 127, 112, 113, 114, 117,
	0, 0, 0, 0, 0, 0, 0, 115, 116, 119,
	118, 120, 121, 122, 123, 124, 125, 126,
}
var yyPact = [...]int{

	1179, -23, -25, 991, -1000, 109, 969, -1000, -1000, -1000,
	1179, -1000, 173, -1000, -1000, -24, 470, 469, -1000, 487,
	-1000, -1000, -1000, -1000, 522, 463, 462, 461, 460, 459,
	-1000, 456, 829, 448, 448, 448, 448, 448, 448, 448,
	448, 448, 448, 448, 448, 448, 448, 448, 448, 448,
	447, 447, 447, 447, 447, 447, 378, 378, 378, 378,
	378, 378, 378, 378, 378, 378, 378, 378, 378, 378,
	378, 378, 378, 947, 20, 918, 233, 308, 882, 132,
	1308, 445, 445, 445, 445, 445, 445, -1000, -1000, -1000,
	-1000, -1000, -1000, 1195, 1195, 1195, 1195, 1195, 1195, 1195,
	661, 1254, -1000, 831, 661, -60, 661, 661, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	569, 555, 554, 180, 552, 551, 544, 335, 1188, 248,
	181, 153, -1000, -1000, -1000, 303, 661, 661, 661, 661,
	541, 313, 969, -1000, -1000, -1000, -1000, 444, 432, 431,
	430, 429, 428, 427, 424, 423, 1187, 422, 1083, 1103,
	-1000, -1000, -1000, -1000, 1083, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 87, 1095, 87, -90,
	-90, -90, -90, 1028, 378, -1000, -1000, -1000, -1000, 1028,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 829, -1000, -1000, -1000, -1000, -1000, 102,
	-1000, 1087, 25, 25, -91, -91, -91, -91, -15, 1195,
	-33, -33, -95, -95, -95, -95, 870, 411, -1000, -1000,
	-1000, -1000, -1000, 661, 661, 661, 661, 661, 777, 719,
	661, 661, 661, 661, 661, 661, 661, 661, 661, 841,
	603, 545, -68, -68, 45, 44, 42, 41, 543, 542,
	32, 29, 28, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 764, 184, 83, 73, 398, -1000, -62, 166,
	0, -1000, 214, -1000, -1000, -1000, -1000, -1000, -1000, 300,
	283, 1254, 1254, 1254, 1254, 1254, 1254, 477, 918, -2,
	272, 18, 1103, -35, 1095, -1000, 1126, 1087, -44, -1000,
	-1000, 1254, -68, -68, -96, -96, -96, -78, -1000, -78,
	-1000, -78, -78, -78, -78, -78, -78, -96, -37, -37,
	-1000, -78, -1000, -78, -1000, -1000, -1000, -1000, -1000, 23,
	14, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 541,
	1331, 0, -1000, -1000, 421, 420, -1000, -1000, -1000, 478,
	110, 89, 261, 217, 205, 193, 163, 183, 370, -1000,
	358, 829, -1000, 778, 358, -1000, -1000, -1000, -1000, -1000,
	-1000, 527, 517, -1000, -1000, -1000, 417, 415, 86, 84,
	80, 72, 525, 49, -1000, 509, -1000, 174, 170, 1254,
	1254, 414, 389, 381, 355, 368, -1000, -1000, 340, 365,
	-1000, -1000, 359, 347, 1254, 1254, 1254, 1254, 483, 1,
	1254, -1000, 494, -1000, -1000, 305, 281, 270, 249, -1000,
	-1000, 316, 230, 160, -1000, -1000, -1000, -1000, 1254, -1000,
	491, 228, 133, -1000, -1000,
}
var yyPgo = [...]int{

	0, 614, 8, 613, 3, 19, 56, 1230, 606, 15,
	9, 1, 415, 198, 5, 14, 605, 10, 940, 604,
	603, 1051, 42, 589, 588, 2, 43, 4, 32, 7,
	0, 21, 587, 6, 586, 581,
}
var yyR1 = [...]int{

	0, 1, 1, 1, 1, 1, 1, 1, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 8, 9, 9,
	9, 9, 9, 9, 9, 9, 9, 2, 3, 4,
	31, 31, 31, 5, 5, 32, 32, 32, 32, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 10, 10,
	11, 12, 12, 12, 12, 12, 12, 20, 20, 21,
	21, 21, 21, 21, 21, 21, 21, 23, 24, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 25, 25, 25, 25, 25, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 14, 14, 16,
	16, 16, 16, 16, 16, 17, 17, 17, 17, 17,
	17, 15, 15, 15, 15, 18, 18, 18, 18, 18,
	18, 18, 18, 19, 19, 33, 35, 34, 34, 26,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	26, 26, 26, 26, 26, 26, 26, 26, 27, 27,
	27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
	27, 27, 27, 27, 28, 28, 28, 28, 28, 28,
	28, 28, 28, 28, 28, 28, 30, 30, 30, 30,
	30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
	30, 30, 30, 30, 29, 29, 29, 29, 29, 29,
	29, 29, 29,
}
var yyR2 = [...]int{

	0, 1, 1, 1, 3, 4, 1, 2, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 3, 1, 1,
	1, 1, 3, 3, 3, 3, 3, 4, 3, 4,
	1, 1, 1, 1, 3, 1, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 1, 2, 3,
	3, 1, 1, 1, 1, 1, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 1, 1, 1,
	2, 2, 2, 3, 4, 4, 4, 4, 3, 7,
	3, 7, 4, 8, 4, 8, 4, 8, 4, 8,
	6, 10, 4, 8, 4, 6, 10, 4, 4, 1,
	1, 1, 1, 1, 1, 2, 2, 2, 3, 3,
	3, 2, 1, 3, 2, 3, 3, 3, 3, 3,
	3, 3, 1, 5, 6, 3, 4, 1, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 2, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 3, 3, 3, 3, 4, 4,
	3, 3, 3,
}
var yyChk = [...]int{

	-1000, -1, -9, -7, -20, -18, -6, -11, -2, -4,
	12, -8, -21, -19, -10, -22, 63, 65, -23, 10,
	-25, 6, 7, 8, 103, 58, 60, 61, 59, 62,
	-35, 78, 79, 80, 86, 84, 90, 91, 81, 92,
	93, 94, 95, 96, 88, 97, 98, 99, 100, 101,
	102, 103, 105, 106, 107, 108, 80, 86, 84, 90,
	91, 81, 92, 93, 94, 88, 96, 95, 97, 98,
	101, 100, 99, -7, -9, -6, -21, -24, -22, -18,
	-12, 102, 103, 105, 106, 107, 108, 82, 83, 84,
	85, 86, 87, -12, 102, 103, 105, 106, 107, 108,
	12, 12, 11, -26, 12, 15, 103, 104, -27, -28,
	-29, -30, 5, 6, 7, 16, 17, 8, 19, 18,
	20, 21, 22, 23, 24, 25, 26, 4, 27, 29,
	30, 31, 33, 32, 34, 35, 37, 38, 39, 40,
	9, 48, 49, 47, 53, 55, 57, 50, 51, 52,
	54, 56, 6, 7, 8, 12, 12, 12, 12, 12,
	12, -13, -6, -11, -2, -3, -4, 67, 68, 69,
	70, 72, 71, 73, 74, 75, 12, 64, -7, 12,
	-7, -7, -7, -7, -7, -7, -7, -7, -7, -7,
	-7, -7, -7, -7, -7, -7, -18, 12, -18, -18,
	-18, -18, -18, -6, 12, -6, -6, -6, -6, -6,
	-6, -6, -6, -6, -6, -6, -6, -6, -6, -6,
	-6, 13, 13, 79, 13, 13, 13, 13, 13, -21,
	-27, 12, -21, -21, -21, -21, -21, -21, -22, 12,
	-22, -22, -22, -22, -22, -22, -26, -5, -31, -28,
	-29, -30, 11, 102, 103, 105, 106, 107, 82, 83,
	84, 85, 86, 87, 89, 88, 108, 80, 81, -26,
	83, 82, -26, -26, 4, 4, 4, 4, 48, 49,
	4, 4, 4, 27, 34, 36, 41, 27, 29, 33,
	30, 31, 41, 44, 28, 29, 45, 42, 43, 29,
	46, 13, -26, -26, -26, -26, -34, -33, 4, -15,
	79, -17, -16, 82, 83, 84, 85, 86, 87, 12,
	12, 12, 12, 12, 12, 12, 12, 12, -6, -22,
	12, -9, 12, -9, 12, -25, -13, 12, -9, 13,
	13, 14, -26, -26, -26, -26, -26, -26, 15, -26,
	15, -26, -26, -26, -26, -26, -26, -26, -26, -26,
	13, -26, 15, -26, 15, 66, 66, 66, 66, 4,
	4, 66, 66, 66, 13, 13, 13, 13, 13, 14,
	82, 79, -17, -14, 76, 77, 6, 7, 8, 103,
	13, 13, -31, -31, -31, -31, -31, -31, -10, 13,
	79, 79, 13, -15, 79, -31, 66, 66, -33, -27,
	-14, 12, 12, 6, 7, 8, 63, 63, 13, 13,
	13, 13, 14, 13, 13, 14, 13, 6, 6, 12,
	12, 63, 63, 63, 63, -32, 7, 6, 63, 6,
	13, 13, -5, -5, 12, 12, 12, 12, 14, 13,
	12, 13, 14, 13, 13, -5, -5, -5, -5, 7,
	6, 63, -5, 6, 13, 13, 13, 13, 12, 13,
	14, -5, 6, 13, 13,
}
var yyDef = [...]int{

	0, -2, 1, 2, 3, 6, 28, 29, 30, 31,
	0, 26, 0, 152, 67, 0, 0, 0, 86, 0,
	96, 97, 98, 99, 0, 0, 0, 0, 0, 0,
	7, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 28, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 71, 72, 73,
	74, 75, 76, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 68, 0, 0, 0, 0, 0, 184, 185,
	186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
	196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
	206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 100, 101, 102, 0, 0, 0, 0, 0,
	0, 4, 32, 33, 34, 35, 36, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 9, 0,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	20, 21, 22, 23, 24, 25, 146, 0, 147, 148,
	149, 150, 151, 50, 0, 51, 52, 53, 54, 55,
	56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
	66, 8, 27, 0, 49, 79, 87, 89, 145, 77,
	78, 0, 80, 81, 82, 83, 84, 85, 70, 0,
	90, 91, 92, 93, 94, 95, 0, 0, 43, 40,
	41, 42, 69, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 182, 183, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 216, 217, 218, 219, 220, 221, 222,
	223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
	233, 103, 0, 0, 0, 0, 0, 157, 0, 5,
	0, 142, 0, 129, 130, 131, 132, 133, 134, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, -2, 0, 0, 0, 37,
	39, 0, 160, 161, 162, 163, 164, 165, 178, 166,
	176, 167, 168, 169, 170, 171, 172, 173, 174, 175,
	159, 177, 180, 179, 181, 234, 235, 236, 237, 0,
	0, 240, 241, 242, 104, 105, 106, 107, 156, 0,
	0, 0, 144, 141, 0, 0, 135, 136, 137, 0,
	108, 110, 0, 0, 0, 0, 0, 0, 0, 38,
	0, 0, 153, 0, 0, 44, 238, 239, 158, 155,
	143, 0, 0, 138, 139, 140, 0, 0, 112, 114,
	116, 118, 0, 122, 124, 0, 154, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 45, 46, 0, 0,
	127, 128, 0, 0, 0, 0, 0, 0, 0, 120,
	0, 125, 0, 109, 111, 0, 0, 0, 0, 47,
	48, 0, 0, 0, 113, 115, 117, 119, 0, 123,
	0, 0, 0, 121, 126,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExpr(yyDollar[1].spansetPipeline)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExpr(yyDollar[1].spansetPipelineExpression)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExpr(yyDollar[1].scalarPipelineExpressionFilter)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExprWithMetrics(yyDollar[1].spansetPipeline, yyDollar[3].metricsAggregation)
		}
	case 5:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExprWithMetricsTwoStage(yyDollar[1].spansetPipeline, yyDollar[3].metricsAggregation, yyDollar[4].metricsSecondStagePipeline)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = yyDollar[1].metricsExpression
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lexer).expr.withHints(yyDollar[2].hints)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = yyDollar[2].spansetPipelineExpression
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetAnd, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnion, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = yyDollar[1].wrappedSpansetPipeline
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.wrappedSpansetPipeline = yyDollar[2].spansetPipeline
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].spansetExpression)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].scalarFilter)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].groupOperation)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].selectOperation)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].spansetExpression)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].scalarFilter)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].groupOperation)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].coalesceOperation)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].selectOperation)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.groupOperation = newGroupOperation(yyDollar[3].fieldExpression)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.coalesceOperation = newCoalesceOperation()
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.selectOperation = newSelectOperation(yyDollar[3].attributeList)
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attribute = yyDollar[1].intrinsicField
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attribute = yyDollar[1].attributeField
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attribute = yyDollar[1].scopedIntrinsicField
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attributeList = []Attribute{yyDollar[1].attribute}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeList = append(yyDollar[1].attributeList, yyDollar[3].attribute)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.numericList = []float64{yyDollar[1].staticFloat}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.numericList = []float64{float64(yyDollar[1].staticInt)}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.numericList = append(yyDollar[1].numericList, yyDollar[3].staticFloat)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.numericList = append(yyDollar[1].numericList, float64(yyDollar[3].staticInt))
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = yyDollar[2].spansetExpression
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetAnd, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnion, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetExpression = yyDollar[1].spansetFilter
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.spansetFilter = newSpansetFilter(NewStaticBool(true))
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetFilter = newSpansetFilter(yyDollar[2].fieldExpression)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpEqual
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpNotEqual
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpLess
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpLessEqual
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpGreater
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpGreaterEqual
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpressionFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpressionFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarPipelineExpression, yyDollar[3].static)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = yyDollar[2].scalarPipelineExpression
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpAdd, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpSub, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpMult, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpDiv, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpMod, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpPower, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = yyDollar[1].wrappedScalarPipeline
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.wrappedScalarPipeline = yyDollar[2].scalarPipeline
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].aggregate)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = yyDollar[2].scalarExpression
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpAdd, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpSub, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpMult, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpDiv, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpMod, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpPower, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = yyDollar[1].aggregate
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticInt(yyDollar[1].staticInt)
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticFloat(yyDollar[1].staticFloat)
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticDuration(yyDollar[1].staticDuration)
		}
	case 100:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticInt(-yyDollar[2].staticInt)
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticFloat(-yyDollar[2].staticFloat)
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticDuration(-yyDollar[2].staticDuration)
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateCount, nil)
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateMax, yyDollar[3].fieldExpression)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateMin, yyDollar[3].fieldExpression)
		}
	case 106:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateAvg, yyDollar[3].fieldExpression)
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateSum, yyDollar[3].fieldExpression)
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateRate, nil)
		}
	case 109:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateRate, yyDollar[6].attributeList)
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateCountOverTime, nil)
		}
	case 111:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateCountOverTime, yyDollar[6].attributeList)
		}
	case 112:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMinOverTime, yyDollar[3].attribute, nil)
		}
	case 113:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMinOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 114:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMaxOverTime, yyDollar[3].attribute, nil)
		}
	case 115:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMaxOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 116:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateSumOverTime, yyDollar[3].attribute, nil)
		}
	case 117:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateSumOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 118:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newAverageOverTimeMetricsAggregator(yyDollar[3].attribute, nil)
		}
	case 119:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newAverageOverTimeMetricsAggregator(yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 120:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateQuantileOverTime(yyDollar[3].attribute, yyDollar[5].numericList, nil)
		}
	case 121:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateQuantileOverTime(yyDollar[3].attribute, yyDollar[5].numericList, yyDollar[9].attributeList)
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateHistogramOverTime, yyDollar[3].attribute, nil)
		}
	case 123:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateHistogramOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 124:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, 10, 0, 0)
		}
	case 125:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, yyDollar[5].staticInt, 0, 0)
		}
	case 126:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, yyDollar[5].staticInt, yyDollar[7].staticInt, yyDollar[9].staticInt)
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsSecondStage = newTopKBottomK(OpTopK, yyDollar[3].staticInt)
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsSecondStage = newTopKBottomK(OpBottomK, yyDollar[3].staticInt)
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpEqual
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpNotEqual
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpLess
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpLessEqual
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpGreater
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpGreaterEqual
		}
	case 135:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.metricsSecondStage = newMetricsFilter(yyDollar[1].scalarFilterOperation, float64(yyDollar[2].staticInt))
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.metricsSecondStage = newMetricsFilter(yyDollar[1].scalarFilterOperation, yyDollar[2].staticFloat)
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.metricsSecondStage = newMetricsFilter(yyDollar[1].scalarFilterOperation, float64(yyDollar[2].staticDuration)/float64(time.Second))
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsSecondStage = newMetricsFilter(yyDollar[1].scalarFilterOperation, float64(-yyDollar[3].staticInt))
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsSecondStage = newMetricsFilter(yyDollar[1].scalarFilterOperation, -yyDollar[3].staticFloat)
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsSecondStage = newMetricsFilter(yyDollar[1].scalarFilterOperation, float64(-yyDollar[3].staticDuration)/float64(time.Second))
		}
	case 141:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.metricsSecondStagePipeline.Append(yyDollar[2].metricsSecondStage, " | ")
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.metricsSecondStagePipeline.Append(yyDollar[1].metricsSecondStage, " ")
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsSecondStagePipeline = yyDollar[1].metricsSecondStagePipeline
			yyVAL.metricsSecondStagePipeline.Append(yyDollar[3].metricsSecondStage, " | ")
		}
	case 144:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.metricsSecondStagePipeline = yyDollar[1].metricsSecondStagePipeline
			yyVAL.metricsSecondStagePipeline.Append(yyDollar[2].metricsSecondStage, " ")
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = yyDollar[2].metricsExpression
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprMath(OpAdd, yyDollar[1].metricsExpression, yyDollar[3].metricsExpression)
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprMath(OpSub, yyDollar[1].metricsExpression, yyDollar[3].metricsExpression)
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprMath(OpMult, yyDollar[1].metricsExpression, yyDollar[3].metricsExpression)
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprMath(OpDiv, yyDollar[1].metricsExpression, yyDollar[3].metricsExpression)
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprMath(OpMod, yyDollar[1].metricsExpression, yyDollar[3].metricsExpression)
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprMath(OpPower, yyDollar[1].metricsExpression, yyDollar[3].metricsExpression)
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.metricsExpression = yyDollar[1].metricsExpression
		}
	case 153:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprWithMetrics(yyDollar[2].spansetPipeline, yyDollar[4].metricsAggregation)
		}
	case 154:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprWithMetricsTwoStage(yyDollar[2].spansetPipeline, yyDollar[4].metricsAggregation, yyDollar[5].metricsSecondStagePipeline)
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.hint = newHint(yyDollar[1].staticStr, yyDollar[3].static)
		}
	case 156:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.hints = newHints(yyDollar[3].hintList)
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.hintList = []*Hint{yyDollar[1].hint}
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.hintList = append(yyDollar[1].hintList, yyDollar[3].hint)
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[2].fieldExpression
		}
	case 160:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpAdd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 161:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpSub, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpMult, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpDiv, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 164:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpMod, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpNotEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 167:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpLess, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 168:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpLessEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 169:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpGreater, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpGreaterEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpNotRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 173:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpPower, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpAnd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 175:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpOr, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 176:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpExists, yyDollar[1].fieldExpression)
		}
	case 177:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpExists, yyDollar[3].fieldExpression)
		}
	case 178:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNotExists, yyDollar[1].fieldExpression)
		}
	case 179:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNotExists, yyDollar[3].fieldExpression)
		}
	case 180:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = NewStaticBool(false)
		}
	case 181:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = NewStaticBool(false)
		}
	case 182:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpSub, yyDollar[2].fieldExpression)
		}
	case 183:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNot, yyDollar[2].fieldExpression)
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].static
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].intrinsicField
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].attributeField
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].scopedIntrinsicField
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticString(yyDollar[1].staticStr)
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticInt(yyDollar[1].staticInt)
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticFloat(yyDollar[1].staticFloat)
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticBool(true)
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticBool(false)
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticDuration(yyDollar[1].staticDuration)
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticStatus(StatusOk)
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticStatus(StatusError)
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticStatus(StatusUnset)
		}
	case 197:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindUnspecified)
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindInternal)
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindServer)
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindClient)
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindProducer)
		}
	case 202:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindConsumer)
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDollar[1].staticStr == "minInt" {
				yyVAL.static = NewStaticInt(math.MinInt)
			} else if yyDollar[1].staticStr == "maxInt" {
				yyVAL.static = NewStaticInt(math.MaxInt)
			} else {
				yylex.(*lexer).Error("unknown identifier: " + yyDollar[1].staticStr)
				yyVAL.static = NewStaticNil()
			}
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicDuration)
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicName)
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicStatus)
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicStatusMessage)
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicKind)
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicParent)
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceRootSpan)
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceRootService)
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceDuration)
		}
	case 213:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetLeft)
		}
	case 214:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetRight)
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetParent)
		}
	case 216:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceDuration)
		}
	case 217:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceRootSpan)
		}
	case 218:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceRootService)
		}
	case 219:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceID)
		}
	case 220:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicDuration)
		}
	case 221:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicName)
		}
	case 222:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicKind)
		}
	case 223:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicStatus)
		}
	case 224:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicStatusMessage)
		}
	case 225:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicSpanID)
		}
	case 226:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicParentID)
		}
	case 227:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicChildCount)
		}
	case 228:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicEventName)
		}
	case 229:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicEventTimeSinceStart)
		}
	case 230:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicLinkTraceID)
		}
	case 231:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicLinkSpanID)
		}
	case 232:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicInstrumentationName)
		}
	case 233:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicInstrumentationVersion)
		}
	case 234:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewAttribute(yyDollar[2].staticStr)
		}
	case 235:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeResource, false, yyDollar[2].staticStr)
		}
	case 236:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeSpan, false, yyDollar[2].staticStr)
		}
	case 237:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeNone, true, yyDollar[2].staticStr)
		}
	case 238:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeResource, true, yyDollar[3].staticStr)
		}
	case 239:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeSpan, true, yyDollar[3].staticStr)
		}
	case 240:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeEvent, false, yyDollar[2].staticStr)
		}
	case 241:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeLink, false, yyDollar[2].staticStr)
		}
	case 242:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeInstrumentation, false, yyDollar[2].staticStr)
		}
	}
	goto yystack /* stack new state and value */
}
