// Code generated by goyacc -l -o pkg/traceql/expr.y.go pkg/traceql/expr.y. DO NOT EDIT.
package traceql

import __yyfmt__ "fmt"

import (
	"math"
	"time"
)

type yySymType struct {
	yys               int
	root              RootExpr
	groupOperation    GroupOperation
	coalesceOperation CoalesceOperation
	selectOperation   SelectOperation
	attributeList     []Attribute

	spansetExpression         SpansetExpression
	spansetPipelineExpression SpansetExpression
	wrappedSpansetPipeline    Pipeline
	spansetPipeline           Pipeline
	spansetFilter             *SpansetFilter
	scalarFilter              ScalarFilter
	scalarFilterOperation     Operator

	scalarPipelineExpressionFilter ScalarFilter
	scalarPipelineExpression       ScalarExpression
	scalarExpression               ScalarExpression
	wrappedScalarPipeline          Pipeline
	scalarPipeline                 Pipeline
	aggregate                      Aggregate
	metricsAggregation             firstStageElement
	metricsSecondStage             secondStageElement
	metricsExpression              *RootExpr

	fieldExpression      FieldExpression
	static               Static
	intrinsicField       Attribute
	attributeField       Attribute
	attribute            Attribute
	scopedIntrinsicField Attribute

	binOp          Operator
	staticInt      int
	staticStr      string
	staticFloat    float64
	staticDuration time.Duration
	numericList    []float64

	hint     *Hint
	hintList []*Hint
	hints    *Hints
}

const IDENTIFIER = 57346
const STRING = 57347
const INTEGER = 57348
const FLOAT = 57349
const DURATION = 57350
const DOT = 57351
const OPEN_BRACE = 57352
const CLOSE_BRACE = 57353
const OPEN_PARENS = 57354
const CLOSE_PARENS = 57355
const COMMA = 57356
const NIL = 57357
const TRUE = 57358
const FALSE = 57359
const STATUS_ERROR = 57360
const STATUS_OK = 57361
const STATUS_UNSET = 57362
const KIND_UNSPECIFIED = 57363
const KIND_INTERNAL = 57364
const KIND_SERVER = 57365
const KIND_CLIENT = 57366
const KIND_PRODUCER = 57367
const KIND_CONSUMER = 57368
const IDURATION = 57369
const CHILDCOUNT = 57370
const NAME = 57371
const STATUS = 57372
const STATUS_MESSAGE = 57373
const PARENT = 57374
const KIND = 57375
const ROOTNAME = 57376
const ROOTSERVICENAME = 57377
const ROOTSERVICE = 57378
const TRACEDURATION = 57379
const NESTEDSETLEFT = 57380
const NESTEDSETRIGHT = 57381
const NESTEDSETPARENT = 57382
const ID = 57383
const TRACE_ID = 57384
const SPAN_ID = 57385
const PARENT_ID = 57386
const TIMESINCESTART = 57387
const VERSION = 57388
const PARENT_DOT = 57389
const RESOURCE_DOT = 57390
const SPAN_DOT = 57391
const TRACE_COLON = 57392
const SPAN_COLON = 57393
const EVENT_COLON = 57394
const EVENT_DOT = 57395
const LINK_COLON = 57396
const LINK_DOT = 57397
const INSTRUMENTATION_COLON = 57398
const INSTRUMENTATION_DOT = 57399
const COUNT = 57400
const AVG = 57401
const MAX = 57402
const MIN = 57403
const SUM = 57404
const BY = 57405
const COALESCE = 57406
const SELECT = 57407
const END_ATTRIBUTE = 57408
const RATE = 57409
const COUNT_OVER_TIME = 57410
const MIN_OVER_TIME = 57411
const MAX_OVER_TIME = 57412
const AVG_OVER_TIME = 57413
const SUM_OVER_TIME = 57414
const QUANTILE_OVER_TIME = 57415
const HISTOGRAM_OVER_TIME = 57416
const COMPARE = 57417
const TOPK = 57418
const BOTTOMK = 57419
const WITH = 57420
const PIPE = 57421
const AND = 57422
const OR = 57423
const EQ = 57424
const NEQ = 57425
const LT = 57426
const LTE = 57427
const GT = 57428
const GTE = 57429
const NRE = 57430
const RE = 57431
const DESC = 57432
const ANCE = 57433
const SIBL = 57434
const NOT_CHILD = 57435
const NOT_PARENT = 57436
const NOT_DESC = 57437
const NOT_ANCE = 57438
const UNION_CHILD = 57439
const UNION_PARENT = 57440
const UNION_DESC = 57441
const UNION_ANCE = 57442
const UNION_SIBL = 57443
const ADD = 57444
const SUB = 57445
const NOT = 57446
const MUL = 57447
const DIV = 57448
const MOD = 57449
const POW = 57450

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"INTEGER",
	"FLOAT",
	"DURATION",
	"DOT",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_PARENS",
	"CLOSE_PARENS",
	"COMMA",
	"NIL",
	"TRUE",
	"FALSE",
	"STATUS_ERROR",
	"STATUS_OK",
	"STATUS_UNSET",
	"KIND_UNSPECIFIED",
	"KIND_INTERNAL",
	"KIND_SERVER",
	"KIND_CLIENT",
	"KIND_PRODUCER",
	"KIND_CONSUMER",
	"IDURATION",
	"CHILDCOUNT",
	"NAME",
	"STATUS",
	"STATUS_MESSAGE",
	"PARENT",
	"KIND",
	"ROOTNAME",
	"ROOTSERVICENAME",
	"ROOTSERVICE",
	"TRACEDURATION",
	"NESTEDSETLEFT",
	"NESTEDSETRIGHT",
	"NESTEDSETPARENT",
	"ID",
	"TRACE_ID",
	"SPAN_ID",
	"PARENT_ID",
	"TIMESINCESTART",
	"VERSION",
	"PARENT_DOT",
	"RESOURCE_DOT",
	"SPAN_DOT",
	"TRACE_COLON",
	"SPAN_COLON",
	"EVENT_COLON",
	"EVENT_DOT",
	"LINK_COLON",
	"LINK_DOT",
	"INSTRUMENTATION_COLON",
	"INSTRUMENTATION_DOT",
	"COUNT",
	"AVG",
	"MAX",
	"MIN",
	"SUM",
	"BY",
	"COALESCE",
	"SELECT",
	"END_ATTRIBUTE",
	"RATE",
	"COUNT_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"HISTOGRAM_OVER_TIME",
	"COMPARE",
	"TOPK",
	"BOTTOMK",
	"WITH",
	"PIPE",
	"AND",
	"OR",
	"EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"NRE",
	"RE",
	"DESC",
	"ANCE",
	"SIBL",
	"NOT_CHILD",
	"NOT_PARENT",
	"NOT_DESC",
	"NOT_ANCE",
	"UNION_CHILD",
	"UNION_PARENT",
	"UNION_DESC",
	"UNION_ANCE",
	"UNION_SIBL",
	"ADD",
	"SUB",
	"NOT",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 321,
	13, 88,
	-2, 96,
}

const yyPrivate = 57344

const yyLast = 1348

var yyAct = [...]int16{
	108, 7, 105, 261, 19, 9, 302, 107, 13, 8,
	250, 251, 252, 261, 96, 317, 2, 83, 366, 242,
	222, 243, 93, 94, 95, 96, 71, 159, 6, 51,
	52, 14, 106, 160, 100, 383, 30, 163, 72, 266,
	265, 161, 75, 253, 254, 255, 256, 257, 258, 260,
	259, 84, 85, 86, 87, 88, 89, 220, 80, 81,
	82, 83, 381, 248, 249, 304, 250, 251, 252, 261,
	31, 91, 92, 435, 93, 94, 95, 96, 217, 217,
	225, 198, 200, 201, 202, 203, 204, 205, 206, 207,
	208, 209, 210, 211, 212, 213, 214, 215, 386, 246,
	385, 20, 21, 22, 359, 18, 245, 173, 358, 91,
	92, 357, 93, 94, 95, 96, 49, 50, 354, 51,
	52, 353, 233, 235, 236, 237, 238, 239, 240, 368,
	369, 244, 241, 352, 351, 412, 264, 408, 267, 268,
	407, 444, 406, 405, 380, 218, 78, 79, 392, 80,
	81, 82, 83, 24, 27, 25, 26, 28, 15, 174,
	16, 247, 164, 165, 166, 167, 169, 168, 170, 171,
	172, 391, 448, 248, 249, 222, 250, 251, 252, 261,
	91, 92, 294, 93, 94, 95, 96, 290, 297, 298,
	299, 300, 84, 85, 86, 87, 88, 89, 23, 295,
	397, 314, 415, 291, 6, 315, 272, 292, 293, 322,
	319, 414, 78, 79, 223, 80, 81, 82, 83, 398,
	160, 396, 6, 321, 163, 447, 327, 314, 161, 395,
	262, 263, 253, 254, 255, 256, 257, 258, 260, 259,
	394, 158, 324, 393, 84, 85, 86, 87, 88, 89,
	273, 274, 248, 249, 6, 250, 251, 252, 261, 443,
	327, 441, 327, 382, 91, 92, 315, 93, 94, 95,
	96, 78, 79, 379, 80, 81, 82, 83, 440, 327,
	439, 327, 371, 328, 329, 330, 331, 332, 333, 335,
	337, 338, 339, 340, 341, 342, 343, 344, 345, 370,
	347, 349, 296, 49, 50, 221, 51, 52, 246, 246,
	246, 246, 246, 246, 90, 245, 245, 245, 245, 245,
	245, 442, 378, 76, 5, 438, 327, 77, 246, 372,
	373, 374, 375, 376, 377, 245, 319, 428, 327, 324,
	244, 244, 244, 244, 244, 244, 72, 424, 72, 384,
	75, 72, 75, 427, 327, 75, 421, 278, 425, 426,
	244, 20, 21, 22, 279, 18, 280, 173, 18, 388,
	199, 281, 387, 193, 195, 196, 197, 423, 422, 399,
	400, 420, 160, 160, 419, 160, 163, 163, 321, 163,
	161, 161, 418, 161, 364, 365, 326, 327, 404, 403,
	390, 389, 316, 313, 246, 246, 312, 311, 310, 309,
	308, 245, 245, 24, 27, 25, 26, 28, 307, 246,
	246, 246, 246, 416, 417, 246, 245, 245, 245, 245,
	306, 305, 245, 226, 194, 176, 244, 244, 429, 430,
	431, 432, 157, 246, 436, 156, 155, 154, 153, 152,
	245, 244, 244, 244, 244, 98, 97, 244, 23, 18,
	434, 433, 445, 411, 410, 124, 109, 110, 111, 114,
	137, 446, 99, 101, 437, 244, 102, 112, 113, 116,
	115, 117, 118, 119, 120, 121, 122, 123, 125, 413,
	126, 127, 128, 130, 129, 131, 132, 402, 133, 134,
	135, 136, 149, 150, 151, 401, 303, 356, 140, 138,
	139, 144, 145, 146, 141, 147, 142, 148, 143, 355,
	277, 276, 275, 124, 109, 110, 111, 114, 137, 271,
	270, 101, 269, 29, 350, 112, 113, 116, 115, 117,
	118, 119, 120, 121, 122, 123, 125, 301, 126, 127,
	128, 130, 129, 131, 132, 409, 133, 134, 135, 136,
	74, 17, 4, 367, 103, 104, 140, 138, 139, 144,
	145, 146, 141, 147, 142, 148, 143, 11, 162, 1,
	0, 124, 109, 110, 111, 114, 137, 0, 0, 101,
	0, 0, 348, 112, 113, 116, 115, 117, 118, 119,
	120, 121, 122, 123, 125, 0, 126, 127, 128, 130,
	129, 131, 132, 0, 133, 134, 135, 136, 0, 0,
	0, 0, 103, 104, 140, 138, 139, 144, 145, 146,
	141, 147, 142, 148, 143, 0, 0, 0, 0, 124,
	109, 110, 111, 114, 137, 0, 0, 101, 0, 0,
	102, 112, 113, 116, 115, 117, 118, 119, 120, 121,
	122, 123, 125, 0, 126, 127, 128, 130, 129, 131,
	132, 0, 133, 134, 135, 136, 0, 0, 0, 0,
	103, 104, 140, 138, 139, 144, 145, 146, 141, 147,
	142, 148, 143, 0, 0, 0, 0, 124, 109, 110,
	111, 114, 137, 0, 0, 101, 0, 0, 336, 112,
	113, 116, 115, 117, 118, 119, 120, 121, 122, 123,
	125, 0, 126, 127, 128, 130, 129, 131, 132, 0,
	133, 134, 135, 136, 0, 0, 0, 0, 103, 104,
	140, 138, 139, 144, 145, 146, 141, 147, 142, 148,
	143, 363, 73, 12, 0, 124, 109, 110, 111, 114,
	137, 0, 0, 101, 0, 0, 334, 112, 113, 116,
	115, 117, 118, 119, 120, 121, 122, 123, 125, 0,
	126, 127, 128, 130, 129, 131, 132, 0, 133, 134,
	135, 136, 362, 0, 0, 0, 103, 104, 140, 138,
	139, 144, 145, 146, 141, 147, 142, 148, 143, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 262, 263,
	253, 254, 255, 256, 257, 258, 260, 259, 361, 0,
	224, 227, 228, 229, 230, 231, 232, 0, 360, 0,
	248, 249, 0, 250, 251, 252, 261, 0, 0, 0,
	0, 0, 0, 0, 103, 104, 0, 0, 0, 262,
	263, 253, 254, 255, 256, 257, 258, 260, 259, 346,
	0, 0, 0, 0, 282, 289, 283, 285, 286, 325,
	284, 248, 249, 0, 250, 251, 252, 261, 287, 0,
	0, 288, 0, 0, 0, 262, 263, 253, 254, 255,
	256, 257, 258, 260, 259, 262, 263, 253, 254, 255,
	256, 257, 258, 260, 259, 219, 0, 248, 249, 0,
	250, 251, 252, 261, 0, 0, 0, 248, 249, 0,
	250, 251, 252, 261, 0, 0, 262, 263, 253, 254,
	255, 256, 257, 258, 260, 259, 262, 263, 253, 254,
	255, 256, 257, 258, 260, 259, 216, 0, 248, 249,
	0, 250, 251, 252, 261, 0, 0, 0, 248, 249,
	0, 250, 251, 252, 261, 0, 0, 0, 0, 0,
	0, 0, 53, 58, 0, 0, 55, 0, 54, 0,
	62, 0, 56, 57, 59, 60, 61, 64, 63, 65,
	66, 69, 68, 67, 55, 0, 54, 0, 62, 0,
	56, 57, 59, 60, 61, 64, 63, 65, 66, 69,
	68, 67, 0, 32, 37, 0, 0, 34, 0, 33,
	0, 43, 0, 35, 36, 38, 39, 40, 41, 42,
	44, 45, 46, 47, 48, 53, 58, 0, 0, 55,
	0, 54, 0, 62, 0, 56, 57, 59, 60, 61,
	64, 63, 65, 66, 69, 68, 67, 32, 37, 0,
	0, 34, 0, 33, 0, 43, 0, 35, 36, 38,
	39, 40, 41, 42, 44, 45, 46, 47, 48, 20,
	21, 22, 0, 18, 0, 173, 0, 20, 21, 22,
	0, 18, 0, 323, 0, 20, 21, 22, 0, 18,
	0, 320, 0, 20, 21, 22, 34, 18, 33, 318,
	43, 0, 35, 36, 38, 39, 40, 41, 42, 44,
	45, 46, 47, 48, 0, 0, 0, 0, 0, 0,
	0, 24, 27, 25, 26, 28, 15, 174, 16, 24,
	27, 25, 26, 28, 15, 0, 16, 24, 27, 25,
	26, 28, 15, 0, 16, 24, 27, 25, 26, 28,
	15, 0, 16, 20, 21, 22, 0, 18, 0, 10,
	0, 20, 21, 22, 0, 0, 23, 234, 0, 0,
	0, 0, 0, 0, 23, 0, 0, 0, 0, 0,
	0, 0, 23, 0, 0, 0, 0, 0, 0, 0,
	23, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	137, 0, 0, 0, 0, 24, 27, 25, 26, 28,
	15, 0, 16, 24, 27, 25, 26, 28, 125, 0,
	126, 127, 128, 130, 129, 131, 132, 0, 133, 134,
	135, 136, 70, 3, 0, 0, 0, 0, 140, 138,
	139, 144, 145, 146, 141, 147, 142, 148, 143, 0,
	23, 0, 0, 0, 0, 0, 0, 0, 23, 0,
	0, 0, 0, 0, 0, 175, 177, 178, 179, 180,
	181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
	191, 192, 124, 109, 110, 111, 114, 0, 0, 0,
	226, 0, 0, 0, 112, 113, 116, 115, 117, 118,
	119, 120, 121, 122, 123, 124, 109, 110, 111, 114,
	0, 0, 0, 0, 0, 0, 0, 112, 113, 116,
	115, 117, 118, 119, 120, 121, 122, 123,
}

var yyPact = [...]int16{
	1167, -42, -9, 987, -1000, 14, 965, -1000, -1000, -1000,
	1167, -1000, 110, -1000, -31, 444, 443, -1000, 461, -1000,
	-1000, -1000, -1000, 496, 437, 436, 435, 434, 433, -1000,
	430, 95, 423, 423, 423, 423, 423, 423, 423, 423,
	423, 423, 423, 423, 423, 423, 423, 423, 423, 422,
	422, 422, 422, 358, 358, 358, 358, 358, 358, 358,
	358, 358, 358, 358, 358, 358, 358, 358, 358, 358,
	943, 66, 902, 44, 292, 162, 201, 1298, 421, 421,
	421, 421, 421, 421, -1000, -1000, -1000, -1000, -1000, -1000,
	1175, 1175, 1175, 1175, 1175, 1175, 1175, 635, 1211, -1000,
	150, 635, -43, 635, 635, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 528, 526, 525,
	202, 518, 517, 516, 330, 847, 158, 165, 153, -1000,
	-1000, -1000, 289, 635, 635, 635, 635, 502, -14, 965,
	-1000, -1000, -1000, -1000, 419, 418, 406, 398, 397, 396,
	395, 394, 391, 355, 390, 1032, 1107, -1000, -1000, -1000,
	-1000, 1032, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -76, 1099, -76, -1000, -1000, 920, 358,
	-1000, -1000, -1000, -1000, 920, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 95, -1000,
	-1000, -1000, -1000, -1000, 169, -1000, 1091, -47, -47, -91,
	-91, -91, -91, 78, 1175, -83, -83, -94, -94, -94,
	-94, 866, 383, -1000, -1000, -1000, -1000, -1000, 635, 635,
	635, 635, 635, 751, 693, 635, 635, 635, 635, 635,
	635, 635, 635, 635, 856, 577, 519, -95, -95, 68,
	67, 55, 52, 515, 503, 45, 42, 38, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 825, 815, 779,
	738, 381, -1000, -64, 53, 286, 269, 1211, 1211, 1211,
	1211, 1211, 1211, 449, 902, 7, 260, 65, 1107, -17,
	1099, -1000, 250, 1091, -44, -1000, -1000, 1211, -95, -95,
	-105, -105, -105, 71, -1000, 71, -1000, 71, 71, 71,
	71, 71, 71, -105, -39, -39, -1000, 71, -1000, 71,
	-1000, -1000, -1000, -1000, -1000, 34, 32, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 502, 1321, -1000, 389, 388,
	108, 85, 230, 227, 216, 208, 186, 206, 366, -1000,
	1083, 95, -1000, 1083, -1000, -1000, -1000, -1000, -1000, 499,
	491, 387, 386, 80, 79, 77, 74, 457, 72, -1000,
	483, 198, 189, 1211, 1211, 380, 372, 369, 344, 364,
	-1000, -1000, 335, 345, -1000, -1000, 340, 324, 1211, 1211,
	1211, 1211, 454, 10, 1211, -1000, 468, -1000, -1000, 312,
	267, 265, 248, -1000, -1000, 309, 246, 127, -1000, -1000,
	-1000, -1000, 1211, -1000, 465, 212, 159, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 579, 9, 578, 5, 19, 27, 1252, 577, 15,
	8, 1, 314, 209, 563, 323, 562, 752, 31, 561,
	560, 4, 34, 2, 32, 7, 0, 21, 555, 6,
	547, 533,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 8, 9, 9,
	9, 9, 9, 9, 9, 9, 9, 2, 3, 4,
	27, 27, 27, 5, 5, 28, 28, 28, 28, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 10, 10,
	11, 12, 12, 12, 12, 12, 12, 16, 16, 17,
	17, 17, 17, 17, 17, 17, 17, 19, 20, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 21, 21, 21, 21, 21, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 13, 13, 13, 13, 13, 13, 14, 14, 15,
	15, 15, 15, 15, 15, 29, 31, 30, 30, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 23, 23,
	23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
	23, 23, 23, 23, 24, 24, 24, 24, 24, 24,
	24, 24, 24, 24, 24, 24, 26, 26, 26, 26,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	26, 26, 26, 26, 25, 25, 25, 25, 25, 25,
	25, 25, 25,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 3, 5, 1, 2, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 3, 1, 1,
	1, 1, 3, 3, 3, 3, 3, 4, 3, 4,
	1, 1, 1, 1, 3, 1, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 1, 2, 3,
	3, 1, 1, 1, 1, 1, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 1, 1, 1,
	2, 2, 2, 3, 4, 4, 4, 4, 3, 7,
	3, 7, 4, 8, 4, 8, 4, 8, 4, 8,
	6, 10, 4, 8, 4, 6, 10, 4, 4, 5,
	3, 3, 3, 3, 3, 3, 4, 1, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 2, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 3, 3, 3, 3, 4, 4,
	3, 3, 3,
}

var yyChk = [...]int16{
	-1000, -1, -9, -7, -16, -15, -6, -11, -2, -4,
	12, -8, -17, -10, -18, 63, 65, -19, 10, -21,
	6, 7, 8, 103, 58, 60, 61, 59, 62, -31,
	78, 79, 80, 86, 84, 90, 91, 81, 92, 93,
	94, 95, 96, 88, 97, 98, 99, 100, 101, 102,
	103, 105, 106, 80, 86, 84, 90, 91, 81, 92,
	93, 94, 88, 96, 95, 97, 98, 101, 100, 99,
	-7, -9, -6, -17, -20, -18, -15, -12, 102, 103,
	105, 106, 107, 108, 82, 83, 84, 85, 86, 87,
	-12, 102, 103, 105, 106, 107, 108, 12, 12, 11,
	-22, 12, 15, 103, 104, -23, -24, -25, -26, 5,
	6, 7, 16, 17, 8, 19, 18, 20, 21, 22,
	23, 24, 25, 26, 4, 27, 29, 30, 31, 33,
	32, 34, 35, 37, 38, 39, 40, 9, 48, 49,
	47, 53, 55, 57, 50, 51, 52, 54, 56, 6,
	7, 8, 12, 12, 12, 12, 12, 12, -13, -6,
	-11, -2, -3, -4, 67, 68, 69, 70, 72, 71,
	73, 74, 75, 12, 64, -7, 12, -7, -7, -7,
	-7, -7, -7, -7, -7, -7, -7, -7, -7, -7,
	-7, -7, -7, -15, 12, -15, -15, -15, -6, 12,
	-6, -6, -6, -6, -6, -6, -6, -6, -6, -6,
	-6, -6, -6, -6, -6, -6, 13, 13, 79, 13,
	13, 13, 13, 13, -17, -23, 12, -17, -17, -17,
	-17, -17, -17, -18, 12, -18, -18, -18, -18, -18,
	-18, -22, -5, -27, -24, -25, -26, 11, 102, 103,
	105, 106, 107, 82, 83, 84, 85, 86, 87, 89,
	88, 108, 80, 81, -22, 83, 82, -22, -22, 4,
	4, 4, 4, 48, 49, 4, 4, 4, 27, 34,
	36, 41, 27, 29, 33, 30, 31, 41, 44, 28,
	29, 45, 42, 43, 29, 46, 13, -22, -22, -22,
	-22, -30, -29, 4, 79, 12, 12, 12, 12, 12,
	12, 12, 12, 12, -6, -18, 12, -9, 12, -9,
	12, -21, -13, 12, -9, 13, 13, 14, -22, -22,
	-22, -22, -22, -22, 15, -22, 15, -22, -22, -22,
	-22, -22, -22, -22, -22, -22, 13, -22, 15, -22,
	15, 66, 66, 66, 66, 4, 4, 66, 66, 66,
	13, 13, 13, 13, 13, 14, 82, -14, 76, 77,
	13, 13, -27, -27, -27, -27, -27, -27, -10, 13,
	79, 79, 13, 79, -27, 66, 66, -29, -23, 12,
	12, 63, 63, 13, 13, 13, 13, 14, 13, 13,
	14, 6, 6, 12, 12, 63, 63, 63, 63, -28,
	7, 6, 63, 6, 13, 13, -5, -5, 12, 12,
	12, 12, 14, 13, 12, 13, 14, 13, 13, -5,
	-5, -5, -5, 7, 6, 63, -5, 6, 13, 13,
	13, 13, 12, 13, 14, -5, 6, 13, 13,
}

var yyDef = [...]int16{
	0, -2, 1, 2, 3, 6, 28, 29, 30, 31,
	0, 26, 0, 67, 0, 0, 0, 86, 0, 96,
	97, 98, 99, 0, 0, 0, 0, 0, 0, 7,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 28, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 71, 72, 73, 74, 75, 76,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 68,
	0, 0, 0, 0, 0, 164, 165, 166, 167, 168,
	169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
	179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
	189, 190, 191, 192, 193, 194, 195, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 100,
	101, 102, 0, 0, 0, 0, 0, 0, 4, 32,
	33, 34, 35, 36, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 9, 0, 10, 11, 12,
	13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
	23, 24, 25, 131, 0, 132, 133, 134, 50, 0,
	51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 8, 27, 0, 49,
	79, 87, 89, 130, 77, 78, 0, 80, 81, 82,
	83, 84, 85, 70, 0, 90, 91, 92, 93, 94,
	95, 0, 0, 43, 40, 41, 42, 69, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 162, 163, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 196, 197,
	198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
	208, 209, 210, 211, 212, 213, 103, 0, 0, 0,
	0, 0, 137, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, -2, 0, 0, 0, 37, 39, 0, 140, 141,
	142, 143, 144, 145, 158, 146, 156, 147, 148, 149,
	150, 151, 152, 153, 154, 155, 139, 157, 160, 159,
	161, 214, 215, 216, 217, 0, 0, 220, 221, 222,
	104, 105, 106, 107, 136, 0, 0, 5, 0, 0,
	108, 110, 0, 0, 0, 0, 0, 0, 0, 38,
	0, 0, 129, 0, 44, 218, 219, 138, 135, 0,
	0, 0, 0, 112, 114, 116, 118, 0, 122, 124,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	45, 46, 0, 0, 127, 128, 0, 0, 0, 0,
	0, 0, 0, 120, 0, 125, 0, 109, 111, 0,
	0, 0, 0, 47, 48, 0, 0, 0, 113, 115,
	117, 119, 0, 123, 0, 0, 0, 121, 126,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExpr(yyDollar[1].spansetPipeline)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExpr(yyDollar[1].spansetPipelineExpression)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExpr(yyDollar[1].scalarPipelineExpressionFilter)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExprWithMetrics(yyDollar[1].spansetPipeline, yyDollar[3].metricsAggregation)
		}
	case 5:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yylex.(*lexer).expr = newRootExprWithMetricsTwoStage(yyDollar[1].spansetPipeline, yyDollar[3].metricsAggregation, yyDollar[5].metricsSecondStage)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yylex.(*lexer).expr = yyDollar[1].metricsExpression
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lexer).expr.withHints(yyDollar[2].hints)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = yyDollar[2].spansetPipelineExpression
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetAnd, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnion, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetNotSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionChild, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionParent, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionDescendant, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionAncestor, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = newSpansetOperation(OpSpansetUnionSibling, yyDollar[1].spansetPipelineExpression, yyDollar[3].spansetPipelineExpression)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipelineExpression = yyDollar[1].wrappedSpansetPipeline
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.wrappedSpansetPipeline = yyDollar[2].spansetPipeline
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].spansetExpression)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].scalarFilter)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].groupOperation)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetPipeline = newPipeline(yyDollar[1].selectOperation)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].spansetExpression)
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].scalarFilter)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].groupOperation)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].coalesceOperation)
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].selectOperation)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.groupOperation = newGroupOperation(yyDollar[3].fieldExpression)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.coalesceOperation = newCoalesceOperation()
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.selectOperation = newSelectOperation(yyDollar[3].attributeList)
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attribute = yyDollar[1].intrinsicField
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attribute = yyDollar[1].attributeField
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attribute = yyDollar[1].scopedIntrinsicField
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.attributeList = []Attribute{yyDollar[1].attribute}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeList = append(yyDollar[1].attributeList, yyDollar[3].attribute)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.numericList = []float64{yyDollar[1].staticFloat}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.numericList = []float64{float64(yyDollar[1].staticInt)}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.numericList = append(yyDollar[1].numericList, yyDollar[3].staticFloat)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.numericList = append(yyDollar[1].numericList, float64(yyDollar[3].staticInt))
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = yyDollar[2].spansetExpression
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetAnd, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnion, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetNotDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 62:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionChild, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionParent, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionSibling, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionAncestor, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetExpression = newSpansetOperation(OpSpansetUnionDescendant, yyDollar[1].spansetExpression, yyDollar[3].spansetExpression)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.spansetExpression = yyDollar[1].spansetFilter
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.spansetFilter = newSpansetFilter(NewStaticBool(true))
		}
	case 69:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.spansetFilter = newSpansetFilter(yyDollar[2].fieldExpression)
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpEqual
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpNotEqual
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpLess
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpLessEqual
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpGreater
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarFilterOperation = OpGreaterEqual
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpressionFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpressionFilter = newScalarFilter(yyDollar[2].scalarFilterOperation, yyDollar[1].scalarPipelineExpression, yyDollar[3].static)
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = yyDollar[2].scalarPipelineExpression
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpAdd, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpSub, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpMult, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpDiv, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpMod, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = newScalarOperation(OpPower, yyDollar[1].scalarPipelineExpression, yyDollar[3].scalarPipelineExpression)
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarPipelineExpression = yyDollar[1].wrappedScalarPipeline
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.wrappedScalarPipeline = yyDollar[2].scalarPipeline
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarPipeline = yyDollar[1].spansetPipeline.addItem(yyDollar[3].aggregate)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = yyDollar[2].scalarExpression
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpAdd, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpSub, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpMult, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpDiv, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpMod, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.scalarExpression = newScalarOperation(OpPower, yyDollar[1].scalarExpression, yyDollar[3].scalarExpression)
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = yyDollar[1].aggregate
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticInt(yyDollar[1].staticInt)
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticFloat(yyDollar[1].staticFloat)
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticDuration(yyDollar[1].staticDuration)
		}
	case 100:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticInt(-yyDollar[2].staticInt)
		}
	case 101:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticFloat(-yyDollar[2].staticFloat)
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scalarExpression = NewStaticDuration(-yyDollar[2].staticDuration)
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateCount, nil)
		}
	case 104:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateMax, yyDollar[3].fieldExpression)
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateMin, yyDollar[3].fieldExpression)
		}
	case 106:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateAvg, yyDollar[3].fieldExpression)
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.aggregate = newAggregate(aggregateSum, yyDollar[3].fieldExpression)
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateRate, nil)
		}
	case 109:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateRate, yyDollar[6].attributeList)
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateCountOverTime, nil)
		}
	case 111:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregate(metricsAggregateCountOverTime, yyDollar[6].attributeList)
		}
	case 112:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMinOverTime, yyDollar[3].attribute, nil)
		}
	case 113:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMinOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 114:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMaxOverTime, yyDollar[3].attribute, nil)
		}
	case 115:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateMaxOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 116:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateSumOverTime, yyDollar[3].attribute, nil)
		}
	case 117:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateSumOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 118:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newAverageOverTimeMetricsAggregator(yyDollar[3].attribute, nil)
		}
	case 119:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newAverageOverTimeMetricsAggregator(yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 120:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateQuantileOverTime(yyDollar[3].attribute, yyDollar[5].numericList, nil)
		}
	case 121:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateQuantileOverTime(yyDollar[3].attribute, yyDollar[5].numericList, yyDollar[9].attributeList)
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateHistogramOverTime, yyDollar[3].attribute, nil)
		}
	case 123:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsAggregateWithAttr(metricsAggregateHistogramOverTime, yyDollar[3].attribute, yyDollar[7].attributeList)
		}
	case 124:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, 10, 0, 0)
		}
	case 125:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, yyDollar[5].staticInt, 0, 0)
		}
	case 126:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.metricsAggregation = newMetricsCompare(yyDollar[3].spansetFilter, yyDollar[5].staticInt, yyDollar[7].staticInt, yyDollar[9].staticInt)
		}
	case 127:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsSecondStage = newTopKBottomK(OpTopK, yyDollar[3].staticInt)
		}
	case 128:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.metricsSecondStage = newTopKBottomK(OpBottomK, yyDollar[3].staticInt)
		}
	case 129:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprWithMetrics(yyDollar[2].spansetPipeline, yyDollar[4].metricsAggregation)
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = yyDollar[2].metricsExpression
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprWithMetricsMath(yyDollar[1].metricsExpression, OpAdd, yyDollar[3].metricsExpression)
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprWithMetricsMath(yyDollar[1].metricsExpression, OpSub, yyDollar[3].metricsExpression)
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprWithMetricsMath(yyDollar[1].metricsExpression, OpMult, yyDollar[3].metricsExpression)
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.metricsExpression = newRootExprWithMetricsMath(yyDollar[1].metricsExpression, OpDiv, yyDollar[3].metricsExpression)
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.hint = newHint(yyDollar[1].staticStr, yyDollar[3].static)
		}
	case 136:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.hints = newHints(yyDollar[3].hintList)
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.hintList = []*Hint{yyDollar[1].hint}
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.hintList = append(yyDollar[1].hintList, yyDollar[3].hint)
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[2].fieldExpression
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpAdd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpSub, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpMult, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpDiv, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpMod, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpNotEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpLess, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpLessEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpGreater, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpGreaterEqual, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpNotRegex, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpPower, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpAnd, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newBinaryOperation(OpOr, yyDollar[1].fieldExpression, yyDollar[3].fieldExpression)
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpExists, yyDollar[1].fieldExpression)
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpExists, yyDollar[3].fieldExpression)
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNotExists, yyDollar[1].fieldExpression)
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNotExists, yyDollar[3].fieldExpression)
		}
	case 160:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = NewStaticBool(false)
		}
	case 161:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.fieldExpression = NewStaticBool(false)
		}
	case 162:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpSub, yyDollar[2].fieldExpression)
		}
	case 163:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.fieldExpression = newUnaryOperation(OpNot, yyDollar[2].fieldExpression)
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].static
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].intrinsicField
		}
	case 166:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].attributeField
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.fieldExpression = yyDollar[1].scopedIntrinsicField
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticString(yyDollar[1].staticStr)
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticInt(yyDollar[1].staticInt)
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticFloat(yyDollar[1].staticFloat)
		}
	case 171:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticBool(true)
		}
	case 172:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticBool(false)
		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticDuration(yyDollar[1].staticDuration)
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticStatus(StatusOk)
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticStatus(StatusError)
		}
	case 176:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticStatus(StatusUnset)
		}
	case 177:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindUnspecified)
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindInternal)
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindServer)
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindClient)
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindProducer)
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.static = NewStaticKind(KindConsumer)
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			if yyDollar[1].staticStr == "minInt" {
				yyVAL.static = NewStaticInt(math.MinInt)
			} else if yyDollar[1].staticStr == "maxInt" {
				yyVAL.static = NewStaticInt(math.MaxInt)
			} else {
				yylex.(*lexer).Error("unknown identifier: " + yyDollar[1].staticStr)
				yyVAL.static = NewStaticNil()
			}
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicDuration)
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicName)
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicStatus)
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicStatusMessage)
		}
	case 188:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicKind)
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicParent)
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceRootSpan)
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceRootService)
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicTraceDuration)
		}
	case 193:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetLeft)
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetRight)
		}
	case 195:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.intrinsicField = NewIntrinsic(IntrinsicNestedSetParent)
		}
	case 196:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceDuration)
		}
	case 197:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceRootSpan)
		}
	case 198:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceRootService)
		}
	case 199:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicTraceID)
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicDuration)
		}
	case 201:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicName)
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicKind)
		}
	case 203:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicStatus)
		}
	case 204:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicStatusMessage)
		}
	case 205:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicSpanID)
		}
	case 206:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicParentID)
		}
	case 207:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicChildCount)
		}
	case 208:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicEventName)
		}
	case 209:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicEventTimeSinceStart)
		}
	case 210:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicLinkTraceID)
		}
	case 211:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicLinkSpanID)
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicInstrumentationName)
		}
	case 213:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.scopedIntrinsicField = NewIntrinsic(IntrinsicInstrumentationVersion)
		}
	case 214:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewAttribute(yyDollar[2].staticStr)
		}
	case 215:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeResource, false, yyDollar[2].staticStr)
		}
	case 216:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeSpan, false, yyDollar[2].staticStr)
		}
	case 217:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeNone, true, yyDollar[2].staticStr)
		}
	case 218:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeResource, true, yyDollar[3].staticStr)
		}
	case 219:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeSpan, true, yyDollar[3].staticStr)
		}
	case 220:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeEvent, false, yyDollar[2].staticStr)
		}
	case 221:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeLink, false, yyDollar[2].staticStr)
		}
	case 222:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.attributeField = NewScopedAttribute(AttributeScopeInstrumentation, false, yyDollar[2].staticStr)
		}
	}
	goto yystack /* stack new state and value */
}
